sudo: required
services:
  - docker
install: docker run -it -v "$PWD":/usr/src -w /usr/src markhobson/node-chrome npm install --unsafe-perm
script: docker run -it -v "$PWD":/usr/src -w /usr/src markhobson/node-chrome npm test
